### ISSUE TITLE
`order by` is lost when it in `union syntax` on global table

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#535]
version: 5.6.29-dble-2.18.02.1-dev-20180428023831
steps:
step1:prepare table
```
mysql> drop table if exists test_global;
$order$4',4),(5,5,'order...5',1);
Query OK, 0 rows affected (0.03 sec)

mysql> drop table if exists global_table2;
Query OK, 0 rows affected (0.22 sec)

mysql> CREATE TABLE test_global(`id` int(10) unsigned NOT NULL,`t_id` int(10) unsigned NOT NULL DEFAULT '0',`name` char(120) NOT NULL DEFAULT '',`pad` int(11) NOT NULL,PRIMARY KEY (`id`),KEY `k_1` (`t_id`))DEFAULT CHARSET=UTF8;
Query OK, 0 rows affected (0.46 sec)

mysql> CREATE TABLE global_table2(`id` int(10) unsigned NOT NULL,`o_id` int(10) unsigned NOT NULL DEFAULT '0',`name` char(120) NOT NULL DEFAULT '',`pad` int(11) NOT NULL,PRIMARY KEY (`id`),KEY `k_1` (`o_id`))DEFAULT CHARSET=UTF8;
Query OK, 0 rows affected (0.46 sec)

mysql> insert into test_global values(1,1,'test中id为1',1),(2,2,'test_2',2),(3,3,'test中id为3',4),(4,4,'$test$4',3),(5,5,'test...5',1),(6,6,'test6',6);
Query OK, 6 rows affected (0.10 sec)
Records: 6  Duplicates: 0  Warnings: 0

mysql> insert into global_table2 values(1,1,'order中id为1',1),(2,2,'test_2',2),(3,3,'order中id为3',3),(4,4,'$order$4',4),(5,5,'order...5',1);
Query OK, 5 rows affected (0.12 sec)
Records: 5  Duplicates: 0  Warnings: 0
```
step2:execute select in dble
```
mysql> (select a.id,a.t_id,a.name,a.pad from test_global a where a.pad=1) union (select c.id,c.o_id,c.name,c.pad from global_table2 c where c.pad=1) order by id limit 2;
+----+------+----------------+-----+
| id | t_id | name           | pad |
+----+------+----------------+-----+
|  1 |    1 | test中id为1    |   1 |
|  5 |    5 | test...5       |   1 |
|  1 |    1 | order中id为1   |   1 |
|  5 |    5 | order...5      |   1 |
+----+------+----------------+-----+
4 rows in set (0.01 sec)
```
step3:execute select in mysql
```
mysql> (select a.id,a.t_id,a.name,a.pad from test_global a where a.pad=1) union (select c.id,c.o_id,c.name,c.pad from global_table2 c where c.pad=1) order by id limit 2;
+----+------+----------------+-----+
| id | t_id | name           | pad |
+----+------+----------------+-----+
|  1 |    1 | order中id为1   |   1 |
|  1 |    1 | test中id为1    |   1 |
+----+------+----------------+-----+
2 rows in set (0.00 sec)
```
step4:explain in dble
```
mysql> explain (select a.id,a.t_id,a.name,a.pad from test_global a where a.pad=1) union (select c.id,c.oo_id,c.name,c.pad from global_table2 c where c.pad=1) order by id limit 2;
+-----------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| DATA_NODE | TYPE     | SQL/REF                                                                                                                                                                                     |
+-----------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| dn1.0     | BASE SQL | (select `a`.`id`,`a`.`t_id`,`a`.`name`,`a`.`pad` from  `test_global` `a` where a.pad = 1) UNION (select `c`.`id`,`c`.`o_id`,`c`.`name`,`c`.`pad` from  `global_table2` `c` where c.pad = 1) |
| merge.1   | MERGE    | dn1.0                                                                                                                                                                                       |
+-----------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
2 rows in set (0.00 sec)
```

**Comment by FlyingMao** [comment]
**Related case：**
1.reference_global.sql：id：59

**Comment by sunsun314** [comment]
fixed in commit 28ed8934b1ae2e07c8bd07a075e50c35d996bccc of master

**Comment by yexiaoli88** [comment]
Issue still exists in **version: 5.6.29-dble-2.18.06.0-20180605085901**

     mysql> (select a.id,a.name,a.status from test_a a where a.status=1) union (select b.id,b.name,b.status 
     from test_b b where b.status=1) order by id;
     +----+----------+--------+
     | id | name     | status |
     +----+----------+--------+
     |  1 | test_b=1 |      1 |
     |  4 | test_b=4 |      1 |
     |  5 | test_b=5 |      1 |
     |  3 | test_b=3 |      1 |
     +----+----------+--------+
     4 rows in set (0.01 sec)

**Comment by yexiaoli88** [comment]
veriified on version: 5.6.29-dble-9.9.9.9-617502e-20180803062203
